### ISSUE TITLE
Make content linkifying optional

### ISSUE THREAD

**Issue by tkirda** [nteract/ansi-to-react#19]
Could you please make linkifying of the content that was recently released optional?

It is causing side effects that are not desired.

**Comment by rgbkrk** [comment]
I certainly agree with that.

/cc @gnestor

**Comment by gnestor** [comment]
https://github.com/nteract/ansi-to-react/issues/20 should resolve this 👍

**Comment by tkirda** [comment]
Awesome! When should I expect new version on NPM?

**Comment by gnestor** [comment]
Released!
