### ISSUE TITLE
Switch to flow instead of prop-types

### ISSUE THREAD

**Issue by lgeiger** [nteract/ansi-to-react#26]
`ansi-to-react` is AFAIK the only nteract module that uses `prop-types` as a direct peer dependency. I think we should switch to flow.

Should we add `ansi-to-react` to the nteract monorepo as well?

**Comment by rgbkrk** [comment]
A+

**Comment by rgbkrk** [comment]
I don't mind it being in the monorepo, however since we know folks are using it we should keep the package name the same.
