### ISSUE TITLE
Improve performance for rendering large amounts of text

### ISSUE THREAD

**Issue by lgeiger** [nteract/ansi-to-react#28]
`Ansi` can be very slow for rendering large amounts of text to the point where `nteract` cannot keep up and crashes.

For me performance issues are appearing when executing anything larger than:
```python
print("This is too large to render smoothly :( "*500000)
```

This seems to be caused by the `Ansi` component even without the linkify option. Improving the performance of [`escape-carriage`](https://github.com/lgeiger/escape-carriage/pull/3) also didn't help 😕

**Comment by rgbkrk** [comment]
Brought up earlier today in https://github.com/nteract/meeting-minutes/blob/master/2017/05-22.md

Perhaps there's some other memoization we can do.

**Comment by ssbarnea** [comment]
Is anyone working to address this? Did you endup using a different library due to performance issues? If so which?

**Comment by rgbkrk** [comment]
I've been a bit away from open source until now, so I apologize for taking this long to let you know -- no one is working on speeding up text rendering currently. It's almost always better to solve it "before" it gets to the rendering (by buffering in advance, memoizing it). What are you using this package with @ssbarnea?

**Comment by ssbarnea** [comment]
No reason to worry anymore as we switched to https://www.npmjs.com/package/react-ansi which is better maintained and does not have the same performance issues.

**Comment by rgbkrk** [comment]
Thanks!
