### ISSUE TITLE
Add support for multilines

### ISSUE THREAD

**Issue by ssbarnea** [nteract/ansi-to-react#34]
Current implementation assumes it will render a single line which is really problematic because ANSI text cannot just be split by line and processed individually, mainly because an escape set on one line will not be reset at the next line.

Another issue with multilines is that i completely breaks the formatting if you feed it multiline strings by combining the lines.

Ideally it should produce results similar to `<pre>` blocks. This means it it should, at least, produce different spans+`<br/>` or <divs> for each line.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @ssbarnea. Would you be interested in submitting a PR for this?

**Comment by ssbarnea** [comment]
I am mostly a Python developer, clearly not JavaScript one. Still, I will have a look, maybe is not rocket science to raise a PR for it.

BTW, The npm listing still links to the 404 old repo location.

**Comment by alex-oren** [comment]
As a workaround, you can define your class as:

```css
code {
    span {
        display: block;  
    }
}
```

**Comment by pbebespoon** [comment]
I just wrap `<Ansi>` inside a `<pre>` and it does the job

**Comment by Izhaki** [comment]
> I just wrap <Ansi> inside a <pre> and it does the job

That seems to do the trick. Close issue?

**Comment by ssbarnea** [comment]
Closing as I am no longer using ansi-to-react
