### ISSUE TITLE
Broken version 6.0.6

### ISSUE THREAD

**Issue by Livan-pro** [nteract/ansi-to-react#38]
Hi! Version 6.0.6 seems broken. There is no `lib` directory, so it can not load. All is fine in 6.0.5.

**Comment by captainsafia** [comment]
Fixed in 6.0.7.

**Comment by vtronxy** [comment]
Version 6.0.8 seems broken. There is no lib directory。 
Node version 12.20.0

**Comment by captainsafia** [comment]
@vtronxy Can you try 6.1.0?
