### ISSUE TITLE
LICENSE file / package.json conflict

### ISSUE THREAD

**Issue by ariel11** [nteract/ansi-to-react#39]
Hi,

On some older versions, the NPM package has the BSD-3-Clause LICENSE file ([example](https://cdn.jsdelivr.net/npm/ansi-to-react@3.3.5/LICENSE)), but then says MPL 2.0 on the package.json ([example](https://cdn.jsdelivr.net/npm/ansi-to-react@3.3.5/package.json)).

Is the package LICENSE just BSD-3-Clause?

Thank you!

**Comment by captainsafia** [comment]
Thanks for bringing this to our attention. The license is indeed BSD-3-Clause. Our package.json needs to be modified.

**Comment by captainsafia** [comment]
It looks like we already use the correct LICENSE versions. The ones that you refer to are from an older version of this package.

**Comment by ariel11** [comment]
Thank you @captainsafia  for the prompt response.  So, could you please confirm what you consider the license to be on the older version?  I am asking because of the open source project called ClearlyDefined, which provides OSS license information for components - https://clearlydefined.io/definitions/npm/npmjs/-/ansi-to-react/3.3.5.  Thank you

**Comment by captainsafia** [comment]
MPL was the license on the older version. Currently, it is on BSD-3.
