### ISSUE TITLE
Github releases are not updated from 2017 

### ISSUE THREAD

**Issue by kapilkumawat86** [nteract/ansi-to-react#40]
Github releases are not updated from 2017... I know you might not be creating release at github side but wanted to see change log and where it is maintained

**Comment by captainsafia** [comment]
This package used to be hosted in this repository until 2017 when it was moved to the nteract monorepo at nteract/nteract.

Recently, we moved the package back to its own repo. You can find the old change logs for it in the mono repo ([ref](https://github.com/nteract/nteract/tree/master/changelogs)).
