### ISSUE TITLE
cant install with react 17

### ISSUE THREAD

**Issue by rafipiccolo** [nteract/ansi-to-react#48]
could u change this in the package.json
to allow react v17 ? 

i can confirm that it works for me with react 17, if i force install, but it would be better to just install without force.

```
"peerDependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  }
```

it could be

```
    "react": "^16.3.2 || ^17.0.0",
    "react-dom": "^16.3.2 || ^17.0.0"
```

**Comment by travigd** [comment]
Make a PR? 😁

**Comment by rafipiccolo** [comment]
done

**Comment by rafipiccolo** [comment]
can u pull and publish the package ?
