### ISSUE TITLE
Module not found: Can't resolve 'ansi-to-react' with next.js

### ISSUE THREAD

**Issue by rafipiccolo** [nteract/ansi-to-react#50]
I have an error when opening page of a project using nextjs :
```
./pages/xxx.js:10:0
Module not found: Can't resolve 'ansi-to-react'
> 10 | import Ansi from "ansi-to-react";
```

versions :
- react 17
- ansi-to-react 6.1.1

I have no error when using ansi-to-react 5

Does anyone have a clue ?

here is the code
```
// pages/xxx.js
import React from 'react'
import Ansi from "ansi-to-react";

function sexylogs() {
    return (
        <Ansi>{'test'}</Ansi>
    );
}
```

**Comment by captainsafia** [comment]
Can you try v6.1.3?

**Comment by rafipiccolo** [comment]
It works thanks !
what did you have to do for it to work ? you just activated npm build ?

**Comment by captainsafia** [comment]
We recently migrated to using `semantic-release` to automatically ship releases of ansi-to-react. Turns out that by default, semantic-release won't publish anything that is in your `.gitignore` (aka the build folder) so had to update the config to properly ship built assets.

**Comment by rafipiccolo** [comment]
Thx
