### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by stevejpurves** [nteract/ansi-to-react#80]
Currently, peer dependencies are set to allow v16 and v17 of `react` and `react-dom`. This prevents projects using this module from upgrading to  v18.

Is it straightforward to also support `^18.0.0`?

**Comment by rowanc1** [comment]
I put a PR up for this, in the interim before this is released, you can add the following to your application `package.json`:

```json
  "overrides": {
    "ansi-to-react": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    }
  }
```

For whichever React version is used by your app.

**Comment by williamstein** [comment]
I merged the pr but didn't close this issue.

**Comment by williamstein** [comment]
I also realize that nobody is ever updating the npm package for this repo.  For what it is worth, I'm maintaining a more maintained fork here:

https://www.npmjs.com/package/@cocalc/ansi-to-react
